### ISSUE TITLE
Ignition Plugin Error

### ISSUE THREAD

**Issue by neverorfrog** [knmcguire/ros_gz_crazyflie#5]
Hi there! Thanks for the amazing work. I'm trying to put up a simple test using your software because I need to implement some flocking algorithms for a university project. The error I'm getting is the following
```
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "Findignition-plugin1.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-plugin1", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-plugin1"
  with any of the following names:

    ignition-plugin1Config.cmake
    ignition-plugin1-config.cmake

  Add the installation prefix of "ignition-plugin1" to CMAKE_PREFIX_PATH or
  set "ignition-plugin1_DIR" to a directory containing one of the above
  files.  If "ignition-plugin1" provides a separate development package or
  SDK, be sure it has been installed.
```

I'm on pop-os 22.04 (everything that works on Ubuntu 22.04 has always worked until now). I've followed [this guide](https://www.bitcraze.io/2024/09/crazyflies-adventures-with-ros-2-and-gazebo/), installing gazebo harmonic and the bridge for ros humble. I've also tried, without success, to install the packages that are apparently missing. 

Thank you in advance

**Comment by knmcguire** [comment]
Hi! Thanks for notifying me ! 

It didn't say which packages it is but I think this is probably ros_gz_crazyflie_gazebo. It has an dependency on the old gazebo ignition, so I've removed that from the cmake assuming that gazebo (new, not ignition) is installed via the instructions. 

Could you remove the lines as in this PR #6 and try again?

**Comment by neverorfrog** [comment]
Alright, now it works! Thanks!

**Comment by knmcguire** [comment]
Awesome! I'll merge the PR. Thanks for testing!
